services:
  - type: web
    name: rabinskiy-sklad-server
    env: node
    buildCommand: npm install && cd server && npm install && npm run build
    startCommand: cd server && node dist/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24
      - key: MOYSKLAD_LOGIN
        value: demo
      - key: MOYSKLAD_PASSWORD
        value: demo
      - key: MOYSKLAD_API_URL
        value: https://api.moysklad.ru/api/remap/1.2
      - key: INIT_DB
        value: false
    autoDeploy: true
    disk:
      name: data
      mountPath: /app/server/data
      sizeGB: 1
    plan: free
    
  - type: redis
    name: rabinskiy-sklad-redis
    ipAllowList: []
    plan: free

  - type: pserv
    name: rabinskiy-sklad-mongodb
    env: docker
    repo: https://github.com/render-examples/mongodb.git
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: admin
      - key: MONGO_INITDB_ROOT_PASSWORD
        generateValue: true
      - key: MONGO_REPLICA_SET_NAME
        value: rs0
    disk:
      name: mongodb-data
      mountPath: /data/db
      sizeGB: 1
    plan: free

databases:
  - name: rabinskiy-sklad-db
    databaseName: rabinskiy-sklad
    user: admin
    plan: free 